### ISSUE TITLE
Bug: Error when try to index block 17823117

### ISSUE THREAD

**Issue by chenzongxiong** [Data-Nexus/rocket-pool-mainnet#3]
![image](https://github.com/Data-Nexus/rocket-pool-mainnet/assets/8354165/346de4de-b9fa-4dad-ad59-d014af9ceb9e)

<img width="1440" alt="image" src="https://github.com/Data-Nexus/rocket-pool-mainnet/assets/8354165/e2993ea3-3d7e-4296-bd49-c9173f43ef5a">

The bug raised due to minipool doesn't be inedexed correctly.

I suspect that the data corruption or any bugs in the subgraph implementation ?

**Comment by Data-Nexus** [comment]
Thanks for reporting. I'll inspect.

**Comment by chenzongxiong** [comment]
any updates?

I also found that, on thegraph official website, the indexing process is also stuck at block 17823117

<img width="1424" alt="image" src="https://github.com/Data-Nexus/rocket-pool-mainnet/assets/8354165/839cc463-6ce5-4de8-8484-804390135bb6">

**Comment by Data-Nexus** [comment]
It appears the address listed for the NodeManagerV3 datasource was incorrect. I'm [syncing ](https://thegraph.com/hosted-service/subgraph/data-nexus/rocket-pool-mainnet?version=pending) a version to see if that now fixes it.

The branch `2.0.1` attempts to resolve.
